### ISSUE TITLE
What is the best approach to support PATCH?

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/rdf-ldp#10]
The existing PATCH approaches I know of are SPARQL 1.1 Update and LDPatch.
- SPARQL 1.1 Update has existing support in RDF.rb, and should be fairly manageable to implement. It would not support update of bnodes within an RDFSource.
- LDPatch has support for bnode update for non-"pathological" graphs (those without ambiguous bnodes), but lacks support in RDF.rb.

Should we aim to pursue Update as an initial format, with the idea that we could also support LDPatch in the future? Are there other options we should consider?

**Comment by jcoyne** [comment]
Yes, SPARQL is a good starting point.

**Comment by gkellogg** [comment]
LDPatch is on my radar, although it's not simply a shim for the SPARQL Algebra, as there are fundamentally different operators involved. However, I suspect it will parse to something which looks like an extension to the SPARQL Algebra.

In the mean time, SPARQL Update is the way to go.

**Comment by no-reply** [comment]
Closing this with two new tickets to track SPARQL Update & LDPatch implementation, respectively.
