### ISSUE TITLE
Support HTTP PATCH with LDPatch format

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/rdf-ldp#12]
At #10, we expressed some interest in supporting LDPatch as a format for HTTP PATCH. Any work on this is dependent on an implementation somewhere upstream in RDF.rb.

**Comment by no-reply** [comment]
An implementation is here: https://github.com/ruby-rdf/rdf-ldp/compare/feature/ld-patch

It depends on a stable release of https://github.com/gkellogg/ld-patch, but otherwise is ready to merge (perhaps with light refactoring).

**Comment by gkellogg** [comment]
Released version 0.1.0 of the ld-patch gem, which passes all (but two intentionally) tests from the LD Patch test suite.
