### ISSUE TITLE
Rethink ETags

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/rdf-ldp#18]
HTTP ETags currently require a full access of the resource _plus_ a [fairly complex hashing function](https://github.com/ruby-rdf/rdf-ldp/blob/develop/lib/rdf/ldp/rdf_source.rb#L115-L137).

We had discussed the possibility of simply storing a `dcterms:modified` timestamp and basing the ETag on that. This option could be much cheaper (depending on the size of the RDFSource's graph), and would open the door to supporting `If-Modified-Since` in #17.

**Comment by gkellogg** [comment]
The hashing implemented there may not even be stable, depending on BNode naming. You probably need rdf-normalization to get it into a stable form, which certainly isn't cheap.

**Comment by cbeer** [comment]
Do you need to base the `ETag` on the content of the graph? Could you just store a suitably random value in `http:etag` (or what have you) on write?

**Comment by no-reply** [comment]
> The hashing implemented there may not even be stable.

Yes. It was always intended as a vaguely plausible hold-over. Cheapness seems important, which is why I didn't consider normalization. The ETags here predate `#metagraph`, so they are very proto-.

> Do you need to base the ETag on the content of the graph?

Nope. A stored, random value would work fine. I'm thinking more something based on the resource URI and last-modified, which kills two birds with one stone (i.e. one stored value for both last-modified and etags). 

If there's a problem with that, please flag it soon. I'll probably implement this week.

**Comment by no-reply** [comment]
Closed by f9357675219
