### ISSUE TITLE
When using lamprey as a gem...

### ISSUE THREAD

**Issue by hectorcorrea** [ruby-rdf/rdf-ldp#29]
According to the README.md this should work:

```
$ gem install rdf-ldp
$ lamprey
```

But instead I get the following error

```
/Users/hjc14/.rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require': cannot load such file -- lamprey (LoadError)
    from /Users/hjc14/.rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
    from /Users/hjc14/.gem/ruby/2.2.2/gems/rdf-ldp-0.3.0/bin/lamprey:3:in `<top (required)>'
    from /Users/hjc14/.gem/ruby/2.2.2/bin/lamprey:23:in `load'
    from /Users/hjc14/.gem/ruby/2.2.2/bin/lamprey:23:in `<main>'
```

**Comment by hectorcorrea** [comment]
However, if I clone the repo the command works, perhaps update the README.md to say

``` sh
$ git clone git@github.com:ruby-rdf/rdf-ldp.git
$ cd ruby-ldp
$ bin/lamprey
```

**Comment by no-reply** [comment]
This seems to be a problem with the require paths. It's failing on: https://github.com/ruby-rdf/rdf-ldp/blob/develop/bin/lamprey#L3

I'll see if I can sort it out.

**Comment by no-reply** [comment]
Looks like `app` isn't getting included in the release: https://github.com/ruby-rdf/rdf-ldp/blob/develop/rdf-ldp.gemspec#L20 

I'll cut a new release to address the issue; though I may take the time to re-run the W3C test suites and update the implementation reports before I do that. 

Sorry for the confusion.

**Comment by no-reply** [comment]
0.4.0 should fix this (and improve a bunch of other things!)
