### ISSUE TITLE
Example on how to post a new resource

### ISSUE THREAD

**Issue by hectorcorrea** [ruby-rdf/rdf-ldp#30]
I am trying to come up with a simple cURL command to post a new resource and the following is giving me "RDF::LDP::NotFound" 

```
curl -X POST -H "Accept: text/turtle" -d demo.ttl localhost:4567
```

Where the content of demo.ttl is

```
<> <http://purl.org/dc/elements/1.1/title> "demo" .
```

Any idea what I need to post to create resource?

The error on the server indicates

```
2015-09-09 17:40:05 - RDF::LDP::NotFound - RDF::LDP::NotFound:
    /Users/hjc14/.gem/ruby/2.2.2/gems/rdf-ldp-0.3.0/lib/rdf/ldp/resource.rb:87:in `find'
    /Users/hjc14/dev/rdf-ldp/app/lamprey.rb:28:in `block in <class:Lamprey>'
```

I have not stepped into the code, I'll try to get to that later, but if you have any ideas I would welcome them.

**Comment by no-reply** [comment]
When you startup Lamprey, You're starting with an empty database. There is no container at the root directory, so `NotFound` is the response you're expecting.

There are two ways to get yourself a Container to get going:
- If all you want is a `BasicContainer` to serve as a root, a simple `GET` to your preferred location does the trick: `curl http://localhost:4567` (this is the method demonstrated in the [README](https://github.com/ruby-rdf/rdf-ldp#lamprey)).
- If you want a different container interaction model or there is already some data in your repository, use a `PUT`, e.g. `curl -i -X PUT -H 'Content-Type: text/turtle' -H 'Link: <http://www.w3.org/ns/ldp#DirectContainer>;rel="type"' -d @container_desc.ttl  http://localhost:4567/my_container`

From there, you should be able to POST. For example, if you've done the GET approach above:

``` bash
curl -i  -X POST -H "Content-Type: text/turtle" -d @demo.ttl localhost:4567
HTTP/1.1 201 Created 
Content-Type: text/turtle
Location: http://localhost:4567/e9723fe6-caa6-43ac-ab17-7ffb73015cdc
Link: <http://www.w3.org/ns/ldp#Resource>;rel="type",<http://www.w3.org/ns/ldp#RDFSource>;rel="type"
Allow: GET, PUT, DELETE, PATCH, OPTIONS, HEAD
Accept-Patch: text/ldpatch,application/sparql-update
Etag: "http://localhost:4567/e9723fe6-caa6-43ac-ab17-7ffb73015cdc2015-09-09T15:28:43.844606-07:00"
Last-Modified: Wed, 09 Sep 2015 22:28:43 GMT
Vary: Accept
X-Content-Type-Options: nosniff
Server: WEBrick/1.3.1 (Ruby/2.1.0/2013-12-25)
Date: Wed, 09 Sep 2015 22:28:43 GMT
Content-Length: 184
Connection: Keep-Alive

@prefix dc11: <http://purl.org/dc/elements/1.1/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://localhost:4567/e9723fe6-caa6-43ac-ab17-7ffb73015cdc> dc11:title "demo" .
```

Note that my `curl` command differs from yours by switching `Content-Type` for `Accept` and prepending `@` to `demo.ttl`.
