### ISSUE TITLE
Skolemize all Bnodes?

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/rdf-ldp#35]
There is a cost to skolemization on the ruby-side, but it removes the issue of blank node compatibility from backends.

I want to add this to make `RDF::Blazegraph` viable for this use case, and add some benchmark specs to make backend tests easy to apply.

**Comment by gkellogg** [comment]
I had been thinking about an"skolemize@ method to Enumerable, that would yield or generate and Enumerable with BNodes replaced with skolem ids. Weed need the reverse operation too. Would this be useful?

**Comment by no-reply** [comment]
Absolutely. Seems better to centralize and optimize. If this ever has to happen on the ruby layer, we should make sure it happens in the best way possible.

**Comment by no-reply** [comment]
Prodding the Blazegraph folks on this: https://jira.blazegraph.com/browse/BLZG-1434

**Comment by no-reply** [comment]
After some more work on this, it seems clear that skolemization is a bad approach.  For the moment, this only affects PATCH. POST, PUT, DELETE are all fine, as long as blank nodes are isolated to a specific `RDFSource`.

I think the whole thing can wait until we get an adequate quad-enabled `RDF::Repository`.
