### ISSUE TITLE
Update dependencies for Rack 2.0

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/rdf-ldp#67]
The main blocker for this is Sinatra, which has updated on [master](https://github.com/sinatra/sinatra/commit/e7ef8e234fd36e389ec7e23d562de488fde7abff#diff-a3ca27ebb62bd740419b3c8a7573e736R18) but is missing a release.

We'll want to decide which range of versions for Rack and Sinatra to support post release. Information on Rack's major release is [thin on the ground](https://github.com/rack/rack/issues/1097), so we may need to do some legwork on this.

**Comment by sandstrom** [comment]
Do you need a full release or does their beta work? (they pushed a beta a few days ago)

https://github.com/sinatra/sinatra/releases/tag/v2.0.0.beta2

**Comment by no-reply** [comment]
This needs a release of `rack-linkeddata` with https://github.com/ruby-rdf/rack-linkeddata/pull/5.

In the meanwhile, there is a branch tracking Sinatra 2.0.0.beta2 at https://github.com/ruby-rdf/rdf-ldp/tree/feature/sinatra-2.0. It looks like we should be able to continue to support both Rack 1.0 and 2.0.

**Comment by no-reply** [comment]
Sinatra 2.0 is now released.
