### ISSUE TITLE
Support creation with PUT

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/rdf-ldp#9]
LDP allows that [LDP servers may choose to allow the creation of new resources using HTTP PUT](http://www.w3.org/TR/ldp/#h-ldpr-put-create).

It's not necessarily clear what the best approach to handling containment would be, if we choose to support this. Other servers handle it in various ways, with visible trade-offs. My inclination is to allow clients to create new, uncontained ("free floating") resources with any interaction model by PUTing to an unused URI.

**Comment by gkellogg** [comment]
Typical POST is used for creating new resources; what's the thought behind also supporting PUT?

**Comment by no-reply** [comment]
POST allows creation of resources within an existing container, but does not allow creating a new container as the root of a separate containment hierarchy.

Some existing LDP servers are not strongly committed to accepting `Slug` hints (actually, the [test suite (erroneously?) requires ambiguous behavior](https://github.com/ruby-rdf/rdf-ldp/issues/6#issuecomment-125093930)). For some of those servers PUT gives a stronger assurance that your resource will be created at the URI you intend.

cf. http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.6

**Comment by jcoyne** [comment]
:+1: Yes it should support PUT.

**Comment by lisp** [comment]
none of the ldp documents describe a recommended way to create a root container, but as it is, by definition, not part of any other resource, put would seem the correct method.

**Comment by no-reply** [comment]
Converting this into a feature ticket, specified as:

> Allow clients to create new, uncontained ("free floating") resources with any interaction model by PUTing to an unused URI.
